// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5qNjWV7APHwj1qYW0rJj0QJuL6g0GM0',
    appId: '1:61466602175:web:0eac6f0d13bf7486adb40a',
    messagingSenderId: '61466602175',
    projectId: 'event-buddy-5b6d1',
    authDomain: 'event-buddy-5b6d1.firebaseapp.com',
    storageBucket: 'event-buddy-5b6d1.firebasestorage.app',
    measurementId: 'G-TG39WXSEMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnpHVY4FdE1lIw6EdbnYt3QeQ21kfGwCc',
    appId: '1:61466602175:android:bdacabdea8d3870dadb40a',
    messagingSenderId: '61466602175',
    projectId: 'event-buddy-5b6d1',
    storageBucket: 'event-buddy-5b6d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxkumCmEa6e17uCpk8oOH61GqmrPqab0',
    appId: '1:61466602175:ios:41eba50fae9efb1cadb40a',
    messagingSenderId: '61466602175',
    projectId: 'event-buddy-5b6d1',
    storageBucket: 'event-buddy-5b6d1.firebasestorage.app',
    iosBundleId: 'com.example.eventbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxkumCmEa6e17uCpk8oOH61GqmrPqab0',
    appId: '1:61466602175:ios:41eba50fae9efb1cadb40a',
    messagingSenderId: '61466602175',
    projectId: 'event-buddy-5b6d1',
    storageBucket: 'event-buddy-5b6d1.firebasestorage.app',
    iosBundleId: 'com.example.eventbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn5qNjWV7APHwj1qYW0rJj0QJuL6g0GM0',
    appId: '1:61466602175:web:8eb719fc44e7ae7dadb40a',
    messagingSenderId: '61466602175',
    projectId: 'event-buddy-5b6d1',
    authDomain: 'event-buddy-5b6d1.firebaseapp.com',
    storageBucket: 'event-buddy-5b6d1.firebasestorage.app',
    measurementId: 'G-PQHL2XGE70',
  );
}
